// SPDX-License-Identifier: MIT
#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define DISPLAY_UPDATE_INTERVAL 50
#define ADC_QUEUE_LENGTH 1
#define ADC_TASK_STACK_SIZE 4096
#define ADC_TASK_PRIORITY 5
#define DISPLAY_TASK_STACK_SIZE 4096
#define DISPLAY_TASK_PRIORITY 4

#define ADC1_QUEUE_LENGTH 8
#define ADC1_TASK_STACK_SIZE 4096
#define ADC1_TASK_PRIORITY 4
#define ADC1_THRESHOLD 900
#define ADC1_HYSTERESIS 20

#define SERVO_GPIO 18
#define SERVO_PWM_HZ 50
#define SERVO_MIN_PULSE_US 500
#define SERVO_MAX_PULSE_US 2500
#define SERVO_MAX_ANGLE_DEG 180
#define SERVO_START_ANGLE_DEG 90
#define SERVO_STEP_DEG 5

#define SERVO_SCAN_MIN_DEG 0
#define SERVO_SCAN_MAX_DEG 180
#define SERVO_SCAN_STEP_DEG 5
#define SERVO_SETTLE_MS 60

#define SERVO_QUEUE_LENGTH 4
#define SERVO_TASK_STACK_SIZE 4096
#define SERVO_TASK_PRIORITY 4

#endif // APP_CONFIG_H
