// SPDX-License-Identifier: MIT
#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define DISPLAY_UPDATE_INTERVAL 50
#define ADC_QUEUE_LENGTH 1
#define ADC_TASK_STACK_SIZE 4096
#define ADC_TASK_PRIORITY 5
#define DISPLAY_TASK_STACK_SIZE 4096
#define DISPLAY_TASK_PRIORITY 4

#endif // APP_CONFIG_H
